### ISSUE TITLE
[JOSS Review]: test coverage too low

### ISSUE THREAD

**Issue by tgoelles** [jdiasn/lidarSuit#47]
35% test coverage is too low. You don't need 100% but certainly more than 35%. 
Please improve the coverage. I have seen that you have it in the makefile.

https://github.com/openjournals/joss-reviews/issues/4852

**Comment by castelao** [comment]
Indeed. Thanks for pointing that out. We will work on it.

**Comment by jdiasn** [comment]
Dear @tgoelles, thank you for your comment! We agree with you that the test coverage is low. We will be working to improve it.
