### ISSUE TITLE
[JOSS review]: follow PEP 8

### ISSUE THREAD

**Issue by tgoelles** [jdiasn/lidarSuit#48]
There is a lot of CamelCase used where it shouldn't.

If you run pylint * in the lidarSuit directory you get a score.
Currently it's 4.07

This is mostly caused by: doesn't conform to snake_case naming style

I suggest increasing the test coverage first and then tackle the names. I guess there is tool out there which does most of the work for you.

https://github.com/openjournals/joss-reviews/issues/4852

**Comment by jdiasn** [comment]
@tgoelles, I agree with you on it. I used CamelCase a lot. We will improve it and use the snake_case instead.

**Comment by jdiasn** [comment]
@tgoelles, thanks for raising this issue. It was indeed an inadequate naming standard. It was addressed and all related PRs were linked here. After those modifications, the current score is around 8.74. I'm closing this issue but please feel free to open it again if I missed anything. Thanks.
